spring.application.name=bodaapp
spring.datasource.url=jdbc:postgresql://localhost:5432/bodaapp
spring.datasource.username=postgres
spring.datasource.password=Alejandro
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Límite máximo para una sola foto (5 Megabytes)
spring.servlet.multipart.max-file-size=7MB

# Límite máximo para toda la petición (Por si envían varios archivos a la vez)
spring.servlet.multipart.max-request-size=7MB